name: "🚀 publish"
on:
  push:
    branches:
      - main # Change this to your default branch
jobs:
  release:
    name: "🚀 publish"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: node
      uses: actions/checkout@v2.1.1
      with:
          node-version: 12
          registry-url: https://registry.npmjs.org
    - name: "🚀 publish"
      run: npm publish --access public
      env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
